name: Maestro Lint CI

on:
  pull_request:
    branches: [main, development/boti, development/nns, stable/nns, stable/boti, release]

jobs:
  lint:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@casamagalhaes'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup github private packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.INSTALL_GITHUB_TOKEN }}" >> .npmrc

      - name: Install Depedencies
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.INSTALL_GITHUB_TOKEN }}

      - name: Run Lint
        run: yarn lint
